name: Build Website

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1

        - name: Setup Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: 3.12

        - name: Upgrade pip, pipenv wheel to latest
          run: |
            python -m pip install --upgrade pip pipenv wheel

        - id: cache-pipenv
          uses: actions/cache@v4
          with:
            path: ~/.local/share/virtualenvs
            key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}

        - name: Install dependencies
          if: steps.cache-pipenv.outputs.cache-hit != 'true'
          run: |
            pipenv install --deploy --skip-lock

        - name: Build website
          run: |
            pipenv run build

        - name: Git add and commit
          run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add docs
            git commit -m "Website Build"
            git push
