name: Build Website if Content Changes

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1

        - name: Setup Python 3.12
          uses: actions/setup-python@v4
          with:
            python-version: 3.12

        - name: Upgrade pip, pipenv wheel to latest
          run: |
            python -m pip install --upgrade pip pipenv wheel

        - id: cache-pipenv
          uses: actions/cache@v4
          with:
            path: ~/.local/share/virtualenvs
            key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}

        - name: Install dependencies
          if: steps.cache-pipenv.outputs.cache-hit != 'true'
          run: |
            pipenv install --deploy --skip-lock

        - name: Build website
          id: build
          run: |
            pipenv run build

        - name: Upload Pages Artifact
          id: push
          uses: actions/upload-pages-artifact@v3
          with:
            path: build/

    deploy:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      needs: build

      permissions:
        pages: write
        id-token: write

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
